name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
    - main

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-auto-assign:
    uses: netcracker/qubership-workflow-hub/.github/workflows/re-pr-assigner.yml@e64a1ee2fc2f68ab44a4ef416c27d83ce36ba8e1 # v2.2.1
