name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
    - main

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-auto-assign:
    uses: netcracker/qubership-workflow-hub/.github/workflows/re-pr-assigner.yml@8c6dbeb901920bae9f40d7d7b646d8d9127e1ce7 # v2.4.0
