name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
    - main

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-auto-assign:
    uses: netcracker/qubership-workflow-hub/.github/workflows/re-pr-assigner.yml@8d542a426ce561c7dce745f6b9cee068d1d7e101 # v2.0.10
